# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]   # Carta coringa, qualquer banch serve
  pull_request:
    branches: [ "*" ]

jobs:
  # 1° roda o test
  test:
    runs-on: ${{ matrix.os }}        # rodar os sistemas
    strategy:
      matrix:
        go_version: ['1.18', '1.19', '>=1.19']    # versões do Go, serem aceitas
        os: ['ubuntu-latest', 'ubuntu-18.04']     # última versão do Ubuntu, versão especifica
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}  # rodar as versões

     # Banco de dados   
    - name: Build-DB
      run: docker-compose build      #  subir banco
      
    - name: Create-DB    
      run: docker-compose up -d      #  criar banco

    # rodar o test
    - name: Test
      run: go test -v main_test.go
      
  
  
  # 2° roda a build
  build:
    needs: test    # ele precisa que o teste de certo, para roda
    runs-on: ${{ matrix.os }}        # rodar os sistemas
    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      run: go build -v main.go
